import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        backgroundDim: "var(--background-dim)",
        backgroundDim2: "var(--background-dim2)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        primaryBright: "var(--primary-bright)",
        primaryDark: "var(--primary-dark)",
        primaryDim: "var(--primary-dim)",
        primaryDim2: "var(--primary-dim2)",
        secondary: "var(--secondary)",
        secondaryBright: "var(--secondary-bright)",
        neon11: "var(--neon-1-1)",
        neon12: "var(--neon-1-2)",
        neon21: "var(--neon-2-1)",
        neon22: "var(--neon-2-2)",
        iconBright: "var(--icon-bright)",
        meshColor1: "var(--mesh-color-1)",
        meshColor2: "var(--mesh-color-2)",
        meshColor3: "var(--mesh-color-3)",
        meshColor4: "var(--mesh-color-4)",
      },
      spacing: {
        "4-": "var(--size-4-)",
        "3-": "var(--size-3-)",
        "2-": "var(--size-2-)",
        "1x": "var(--size-1x)",
        "2x": "var(--size-2x)",
        "3x": "var(--size-3x)",
        "4x": "var(--size-4x)",
        "5x": "var(--size-5x)",
        "6x": "var(--size-6x)",
        "7x": "var(--size-7x)",
      },
      fontSize: {
        "xx": "var(--font-xx)",
        "xs": "var(--font-xs)",
        "s": "var(--font-s)",
        "r-s": "var(--font-r-s)",
        "r": "var(--font-r)",
        "m": "var(--font-m)",
        "l": "var(--font-l)",
        "xl-l": "var(--font-xl-l)",
        "xl": "var(--font-xl)",
      },
      brightness: {
        low: "var(--brightness-low)",
        high: "var(--brightness-high)",
      },
    },
  },
  plugins: [],
} satisfies Config;
